security:
  jwt:
    secret: secret
    access: 1
    refresh: 30
user:
  client:
    url: http://localhost:8080/api
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}




