CREATE SCHEMA auth_schema;
CREATE TABLE auth_schema.auth_role
(
    auth_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE auth_schema.auths
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_auth PRIMARY KEY (id)
);

ALTER TABLE auth_schema.auth_role
    ADD CONSTRAINT fk_auth_role_on_auth_entity FOREIGN KEY (auth_id) REFERENCES auth_schema.auths (id);