server:
  servlet:
    contextPath: ${ROOT_URL:/api}
  port: 8084

spring:
  application:
    name: health-server
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:health_database}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

auth:
  server:
    URI: ${AUT_SERVER_URI:http://localhost:8080/api/auth}

bigchaindb:
  URI: {$BIGCHAIN_DB_URI:http://localhost:9984}